[package]
name = "signrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.12"
rhai = {version = "1.13", features = ["f32_float"]}
notify = "5.1.0"
thiserror = "1.0"